# Numpy:
  * numpy---numerical python.
  * numpy is a library in python which is used to built different dimensional arrays.

In [1]:
import numpy as np
a=[1,2,3,4,5]
data=np.array(a)
print(data)

[1 2 3 4 5]


In [2]:
a

[1, 2, 3, 4, 5]

In [3]:
data1=np.array([[1,2,3],[4,5,6]])

In [4]:
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
data1.shape

(2, 3)

In [5]:
type(data1)

numpy.ndarray

In [6]:
data2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
data2.shape

(3, 3)

In [12]:
#arranging data in a array
data=np.arange(0,100)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
data.shape

(100,)

In [15]:
data2=data.reshape(10,10)
data2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [16]:
data2=np.linspace(0,8,10)
data2

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [17]:
data2.shape

(10,)

In [22]:
data=np.random.randint(0,20,size=(2,4))
data

array([[ 1,  7, 15,  7],
       [ 1, 18, 14, 10]])

In [24]:
data=np.ones((4,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
data=np.ones((4,3),int)
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
data=np.zeros((4,3),int)
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
n=np.ones((4,3),int)
n
np.vstack([n,n*10])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [ 1,  1,  1],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [32]:
n=np.ones((4,3),int)
n
np.hstack([n,n*2])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## operators:


In [33]:
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
n1+n2

array([ 6,  8, 10, 12])

In [34]:
n1-n2

array([-4, -4, -4, -4])

In [35]:
n1*n2

array([ 5, 12, 21, 32])

In [36]:
n1/n2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [37]:
n1**n2

array([    1,    64,  2187, 65536], dtype=int32)

In [38]:
n1%n2

array([1, 2, 3, 4], dtype=int32)

In [39]:
n1 & n2

array([1, 2, 3, 0], dtype=int32)

In [40]:
n1.dot(n2)

70

In [42]:
data1=np.array([[1,2,3,4],[4,5,6,7]])
data1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [43]:
data1.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [44]:
print(data1.transpose())

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [45]:
data1.min()

1

In [46]:
data1.max()

7

In [47]:
data1.sum()

32

In [48]:
data1.mean()

4.0