# numpy

In [1]:
l=[1,2,3,4]

In [2]:
import numpy as np
b=np.array(l)

In [3]:
b

array([1, 2, 3, 4])

In [4]:
c=np.array([l,b])

In [5]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
c.size

8

In [7]:
c.itemsize

4

In [8]:
c.shape

(2, 4)

In [9]:
c.ndim

2

In [10]:
a=np.arange(1,10)

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a.resize?

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.resize((3,3),refcheck=True)

In [17]:
a.size

9

In [18]:
k=np.array([[1,2,3,4],[5,6,7,8]])

In [19]:
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
v=np.random.rand(3,2)

In [27]:
v

array([[0.96269667, 0.23858266],
       [0.12972108, 0.73307022],
       [0.30521976, 0.21489617]])

In [28]:
v=np.random.randn(3,2)

In [29]:
v

array([[-0.38345406,  1.00896253],
       [ 0.11949409,  0.11421857],
       [ 0.15883017, -0.46652717]])

In [37]:
np.random?

In [35]:
v=np.random.ranf(4)

In [36]:
v

array([0.73419998, 0.09216353, 0.87605795, 0.47774806])

In [40]:
v=np.random.randint(3)

In [42]:
v

1

In [43]:
p=np.array([[1,2,3],[3,4,5]])
q=np.array([[6,7,8],[2,5,4]])
p+q

array([[ 7,  9, 11],
       [ 5,  9,  9]])

In [44]:
p-q

array([[-5, -5, -5],
       [ 1, -1,  1]])

In [45]:
p*q

array([[ 6, 14, 24],
       [ 6, 20, 20]])

In [46]:
p^q

array([[ 7,  5, 11],
       [ 1,  1,  1]], dtype=int32)

In [47]:
p^p

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
np.mean(l)

2.5

In [60]:
np.var(l)

1.25

In [61]:
np.std(l)

1.118033988749895

In [62]:
np.sum(l)

10

In [64]:
np.cumsum(c,axis=1)

array([[ 1,  3,  6, 10],
       [ 1,  3,  6, 10]], dtype=int32)

In [65]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [66]:
np.cumsum(c,axis=0)

array([[1, 2, 3, 4],
       [2, 4, 6, 8]], dtype=int32)

In [68]:
np.cumprod(c,axis=0)

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]], dtype=int32)

In [69]:
np.sqrt(c)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [70]:
np.max(c)

4

In [71]:
np.min(c)

1

In [72]:
np.argmax(c)

3

In [73]:
np.argmin(c)

0

In [76]:
c.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [77]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [81]:
np.invert(c)

array([[-2, -3, -4, -5],
       [-2, -3, -4, -5]], dtype=int32)

In [82]:
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [83]:
c[1:]

array([[1, 2, 3, 4]])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [86]:
a[1,2]

6

In [87]:
a[1,:]

array([4, 5, 6])

In [88]:
a[2,:]

array([7, 8, 9])

In [90]:
a[:,1]

array([2, 5, 8])

In [93]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [95]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
np.array([1,2,3,4],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [100]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.linspace(2,3,10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [106]:
np.linspace(2,3,15)

array([2.        , 2.07142857, 2.14285714, 2.21428571, 2.28571429,
       2.35714286, 2.42857143, 2.5       , 2.57142857, 2.64285714,
       2.71428571, 2.78571429, 2.85714286, 2.92857143, 3.        ])

# pandas

In [107]:
import pandas as pd

In [108]:
a=pd.Series([1,2,3,4])

In [109]:
a

0    1
1    2
2    3
3    4
dtype: int64

In [112]:
a=pd.Series([1,2,3,4],[4,5,6,7])

In [113]:
a

4    1
5    2
6    3
7    4
dtype: int64

In [114]:
a=pd.DataFrame(a)

In [115]:
a

0
4  1
5  2
6  3
7  4

In [124]:
a={'name':['keerthi','siri','haritha'],'rollno':[511,522,530]}
a=pd.DataFrame(a)

In [125]:
a.set_index('rollno')

name
rollno         
511     keerthi
522        siri
530     haritha

In [126]:
a.drop('name',axis=1)

rollno
0     511
1     522
2     530

In [127]:
a['name']=['keerthi','siri','haritha']

In [128]:
a

name  rollno
0  keerthi     511
1     siri     522
2  haritha     530